@extends('layouts.client')


@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ">
            <div class="delivery-form-heading">
                <h4 class="text-center">Privacy Policy</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ">
            <div class="policy-content">
                <p>
                    Always Healthy Pharma cares about you and knows that you care how your information is used and or may be used or shared. By visiting https://alwayshealthypharma.com/ , you are accepting and consenting to the practices described in this Privacy Policy. This policy is issued by Axelia Solutions Private Limited.

                </p>
                <p>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

                </p>
                <p>
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.always healthy pharma.in website and its mobile applications.

                </p>
                <p>
                    By using this Website, you agree to the terms and conditions of this Privacy Policy. If you do not agree with the Terms and Conditions of this Privacy Policy, please do not proceed further to use this Website. This Privacy Policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically. This Privacy Policy is incorporated into and subject to the Terms of Use.

                </p>
                <p>
                    For the purpose of this Privacy Policy, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Personal Information (defined below) while registering on the Website as a registered User using the computer systems..
                </p>

            </div>

            <div class="sub-policy-heading">
                <h6>1. What Personal Information About You Does always healthy pharma collect?</h6>
            </div>
            <div class="heading-content">
                <p>
                    The information we learn from customers helps us personalise and continuously improve your experience at always healthy pharma. Your information so collected may be used to assist retailers in handling orders, delivery through your agent and ancillary services, process payments, communicate with you about orders, products, services and promotional offers, update our records and generally maintain your accounts with us. We also use this information to improve our platform, prevent or detect fraud or abuses of our website and enable third parties to carry out technical, logistical or other functions on our behalf.

                </p>
                <p>
                    Given below are the types of information that we may collect:
                </p>
                <p>

                    Permission You give Us: We use third party SDKs in our app. Majority of them are different payment options by which You can make a payment for an order. In order to enhance Your personal and overall experience some of the tools are used therein.

                </p>
                <p>
                    Third Party tools: We use third party SDKs in our app. Majority of them are different payment options by which You can make a payment for an order. In order to enhance Your personal and overall experience some of the tools are used therein.

                </p>
                <p>
                    order Medicine, order OTC products, book a doctor consultation, schedule diagnostic test, etc., Prescription for medicine order or diagnostic test, Patient details, Diseases for doctor consultation, Address, Phone Number, Email id) to see examples of what we collect. You can choose not to provide certain information but then you might not be able to take advantage of many of our features. We use the information that you provide for such purposes as responding to your requests, customising your orders, improving our platform, communicating with you.

                </p>
                <p>
                    Information from Other Sources: We might receive information about you from other sources and add it to our account information.

                    Automatic Information: We receive and store certain types of information whenever you interact with us. For example, we obtain certain types of information when your Web browser accesses always healthy pharma.in or advertisements and other content served by or on behalf of always healthy pharma.in on other Web sites. Click here (OS type and version, App version, Device brand, Browser and its version details, User Agent) to see examples of the information we receive. We may also receive/store information about your location and your mobile device, including a unique identifier for your device. We may use this information for internal analysis and to provide you with location-based services, such as advertising, search results, and other personalized content.

                </p>

                <p>
                    By using or continuing to use the always healthy pharma site You agree to our use of Your information in accordance with this Privacy Policy, as may be amended from time to time by always healthy pharma at its discretion (including sensitive personal information as per Rule 5(2)(b) of the Information Technology {Reasonable Security Practices & Procedures and Sensitive Personal Data or Information } Rules, 2011 or SPDI Rules). Sensitive Personal Data or Information “SPDI” so collected and retained (either internally or third-party servers) is necessary for the purposes identified in this Privacy Policy and for providing the services. No unnecessary or additional information is asked for by always healthy pharma. You also agree and consent to us collecting, storing, processing, transferring and sharing information (including sensitive personal information) related to you with third parties or service providers for the purposes as set out in this Privacy Policy.

                </p>
            </div>

            <div class="sub-policy-heading">
                <h6>2. Does always healthy pharma.in share the Information it receives</h6>
            </div>
            <div class="heading-content">
                <p>
                    Information about You and the other users of always healthy pharma forms an integral part of our business. always healthy pharma may only share the customer information as described below after ensuring that such third party has implemented measures to assure data protection measures and that are either subject to this Privacy Policy or follow practices at least as protective as those described in this Privacy Policy. always healthy pharma has arrangements with third parties (as mentioned below) such as service providers, retailers, payment gateways, logistics partners who may have access to the SPDI but shall not disclose such SPDI further to any other individual / entity.

                </p>
                <p>
                    Retail partners we have tied up with: : We work closely with affiliated retailers who supply and service your order. These retailers operate at always healthy pharma.in or sell medicines and wellness products to you at always healthy pharma.in. You can tell when a third party is involved in your transactions and we share customer information related to those transactions with that third party.

                </p>
                <p>
                    Third Party Service Providers: We have tied up with third party service providers, retailers and logistics providers for the fulfilment and delivery of your order(s). Examples include fulfilling orders, delivering packages, sending postal mail and e-mail, removing repetitive information from customer lists, analysing data, providing marketing assistance, providing search results and links (including paid listings and links), processing card payments and providing customer service. They have access to personal information needed to perform their functions, but may not use it for other purposes. Further, they must process the personal information in accordance with this Privacy Policy and as permitted by applicable law.
                </p>
                <p>
                    Protection of always healthy pharma.in and Others: We release account and other personal information when we believe release is appropriate to comply with applicable law; enforce or apply our Conditions of Use and other agreements; or protect the rights, property or safety of always healthy pharma.in , our users or others. This includes exchanging information with other companies, organisations, government or regulatory authorities for fraud protection and credit risk reduction. Obviously, however, this does not include selling, renting, sharing or otherwise disclosing personally identifiable information from customers for commercial purposes in a way that is contrary to the commitments made in this Privacy Policy. We may share generic aggregated demographic information not linked to any personal information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above. We may use third party service providers to help us operate our business and the site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes.

                </p>
                <p>
                    With your consent: Other than as set out above, you will receive notice when personally identifiable information about you might go to third parties and you will have an opportunity to choose not to share such personally identifiable information
                </p>

            </div>


            <div class="sub-policy-heading">
                <h6>3. How Secure Is Information About Me?</h6>
            </div>
            <div class="heading-content">
                <p>
                    We maintain electronic, physical and procedural safeguards in connection with the collection, storage and disclosure of personal information (including sensitive personal information). Our security procedures mean that we may occasionally request proof of identity before we disclose personal information to you.

                </p>
                <p>
                    We work to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you input in addition to maintaining security of your information as per the International Standard IS/ISO/IEC 27001 on "Information Technology Security Techniques Information Security Management System-Requirements".

                </p>
                <p>
                    Under certain circumstances, always healthy pharma shall not be able to take Your prior consent before disclosing Your information in case the information is demanded by government agencies mandated under law to obtain SPDI, or during investigation of cyber incidents, prosecution of offenses etc.

                </p>
                <p>
                    always healthy pharma shall not publish SPDI and keep all information confidential (subject to exceptions where mandated by law or an order of a Court)
                </p>
            </div>

            <div class="sub-policy-heading">
                <h6>4. What Information Can I Access?</h6>
            </div>
            <div class="heading-content">
                <p>
                    always healthy pharma.in gives you access to a broad range of information about Your account and Your interactions with always healthy pharma.in for the limited purpose of viewing and, in certain cases, modifying, deleting information provided to always healthy pharma. You have the option to opt-out of optional services such as receiving promotional materials etc. and should You desire to opt-in to such services at the time of signing up You can choose do so.

                </p>
                <p>
                    This list will change as our website evolves.
                </p>

            </div>


            <div class="sub-policy-heading">
                <h6>5. Are Children Allowed to Use always healthy pharma.in?</h6>
            </div>
            <div class="heading-content">
                <p>
                    Use of always healthy pharma.in is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 years, you may use always healthy pharma.in only with the involvement of a parent or guardian.

                </p>
            </div>


            <div class="sub-policy-heading">
                <h6>6. Notices and Revisions</h6>
            </div>
            <div class="heading-content">
                <p>
                    If you have any concern about privacy or grievances at always healthy pharma.in , please contact us with a thorough description and we will try to resolve the issue for you.

                </p>
                <p>
                    Our business changes constantly and our Privacy Policy and the Conditions of Use will change also. You should check our website frequently to see recent changes.
                </p>
                <p>
                    Unless stated otherwise, our current Privacy Policy applies to all information that we have about you and your account. We stand behind the promises we make, however, and will never materially change our policies and practices to make them less protective of customer information collected in the past without the consent of affected customers
                </p>

                <p>
                    If you have any concerns or questions in relation to this Privacy Policy, you may address them to our grievance officer at:

                    Pramod Nair <b>Contact number: 7039442999</b>
                </p>
                <p>
                    E-mail: alwayshealthypharma@gmail.com

                    always healthy pharma shall endeavour to resolve Your grievances within one month from the date of receipt of such grievance.
                </p>
            </div>

        </div>

    </div>
</div>




</div>
</div>
</div>


@endsection